# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QGraphicsView.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1073, 900)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.data_info = QtWidgets.QTextBrowser(self.centralwidget)
        self.data_info.setGeometry(QtCore.QRect(20, 530, 281, 81))
        self.data_info.setMinimumSize(QtCore.QSize(281, 81))
        self.data_info.setObjectName("data_info")
        self.index = PlotWidget(self.centralwidget)
        self.index.setGeometry(QtCore.QRect(20, 380, 991, 121))
        self.index.setMinimumSize(QtCore.QSize(991, 121))
        self.index.setObjectName("index")
        self.breath = PlotWidget(self.centralwidget)
        self.breath.setGeometry(QtCore.QRect(20, 80, 991, 121))
        self.breath.setMinimumSize(QtCore.QSize(991, 121))
        self.breath.setObjectName("breath")
        self.heart = PlotWidget(self.centralwidget)
        self.heart.setGeometry(QtCore.QRect(20, 230, 991, 121))
        self.heart.setMinimumSize(QtCore.QSize(991, 121))
        self.heart.setObjectName("heart")
        self.breath_label = QtWidgets.QLabel(self.centralwidget)
        self.breath_label.setGeometry(QtCore.QRect(20, 60, 91, 16))
        self.breath_label.setObjectName("breath_label")
        self.int_label = QtWidgets.QLabel(self.centralwidget)
        self.int_label.setGeometry(QtCore.QRect(20, 360, 71, 16))
        self.int_label.setObjectName("int_label")
        self.heart_label = QtWidgets.QLabel(self.centralwidget)
        self.heart_label.setGeometry(QtCore.QRect(20, 210, 91, 16))
        self.heart_label.setObjectName("heart_label")
        self.data_info_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.data_info_2.setGeometry(QtCore.QRect(340, 750, 451, 101))
        self.data_info_2.setMinimumSize(QtCore.QSize(451, 101))
        self.data_info_2.setObjectName("data_info_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(850, 550, 121, 199))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.prev_b = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.prev_b.setMinimumSize(QtCore.QSize(119, 23))
        self.prev_b.setObjectName("prev_b")
        self.verticalLayout.addWidget(self.prev_b)
        self.next_b = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.next_b.setMinimumSize(QtCore.QSize(119, 23))
        self.next_b.setObjectName("next_b")
        self.verticalLayout.addWidget(self.next_b)
        self.undo_b = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.undo_b.setMinimumSize(QtCore.QSize(119, 23))
        self.undo_b.setObjectName("undo_b")
        self.verticalLayout.addWidget(self.undo_b)
        self.redo_b = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.redo_b.setMinimumSize(QtCore.QSize(119, 23))
        self.redo_b.setObjectName("redo_b")
        self.verticalLayout.addWidget(self.redo_b)
        self.nu_b = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.nu_b.setMinimumSize(QtCore.QSize(119, 23))
        self.nu_b.setObjectName("nu_b")
        self.verticalLayout.addWidget(self.nu_b)
        self.fu_b = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.fu_b.setMinimumSize(QtCore.QSize(119, 23))
        self.fu_b.setObjectName("fu_b")
        self.verticalLayout.addWidget(self.fu_b)
        self.refresh_b = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.refresh_b.setMinimumSize(QtCore.QSize(119, 23))
        self.refresh_b.setObjectName("refresh_b")
        self.verticalLayout.addWidget(self.refresh_b)
        self.input_data_path = QtWidgets.QTextEdit(self.centralwidget)
        self.input_data_path.setGeometry(QtCore.QRect(20, 10, 351, 31))
        self.input_data_path.setMinimumSize(QtCore.QSize(351, 31))
        self.input_data_path.setObjectName("input_data_path")
        self.action_info = QtWidgets.QTextBrowser(self.centralwidget)
        self.action_info.setGeometry(QtCore.QRect(340, 700, 451, 41))
        self.action_info.setMinimumSize(QtCore.QSize(451, 41))
        self.action_info.setObjectName("action_info")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(340, 500, 391, 181))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.class_abn_b = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.class_abn_b.setMinimumSize(QtCore.QSize(128, 111))
        self.class_abn_b.setObjectName("class_abn_b")
        self.horizontalLayout.addWidget(self.class_abn_b)
        self.class_n_b = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.class_n_b.setMinimumSize(QtCore.QSize(129, 111))
        self.class_n_b.setObjectName("class_n_b")
        self.horizontalLayout.addWidget(self.class_n_b)
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton.setMinimumSize(QtCore.QSize(128, 111))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.set_data_path = QtWidgets.QPushButton(self.centralwidget)
        self.set_data_path.setGeometry(QtCore.QRect(740, 10, 101, 23))
        self.set_data_path.setMinimumSize(QtCore.QSize(101, 23))
        self.set_data_path.setObjectName("set_data_path")
        self.input_work_path = QtWidgets.QTextEdit(self.centralwidget)
        self.input_work_path.setGeometry(QtCore.QRect(380, 10, 351, 31))
        self.input_work_path.setMinimumSize(QtCore.QSize(351, 31))
        self.input_work_path.setObjectName("input_work_path")
        self.set_work_path = QtWidgets.QPushButton(self.centralwidget)
        self.set_work_path.setGeometry(QtCore.QRect(850, 10, 111, 23))
        self.set_work_path.setMinimumSize(QtCore.QSize(111, 23))
        self.set_work_path.setObjectName("set_work_path")
        self.data_list = QtWidgets.QListWidget(self.centralwidget)
        self.data_list.setGeometry(QtCore.QRect(20, 710, 281, 141))
        self.data_list.setMinimumSize(QtCore.QSize(281, 141))
        self.data_list.setObjectName("data_list")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1073, 23))
        self.menubar.setObjectName("menubar")
        self.menustart = QtWidgets.QMenu(self.menubar)
        self.menustart.setObjectName("menustart")
        self.menuopen_recent = QtWidgets.QMenu(self.menustart)
        self.menuopen_recent.setObjectName("menuopen_recent")
        MainWindow.setMenuBar(self.menubar)
        self.actionopendir = QtWidgets.QAction(MainWindow)
        self.actionopendir.setObjectName("actionopendir")
        self.actionopenfile = QtWidgets.QAction(MainWindow)
        self.actionopenfile.setObjectName("actionopenfile")
        self.actionundo = QtWidgets.QAction(MainWindow)
        self.actionundo.setObjectName("actionundo")
        self.actionredu = QtWidgets.QAction(MainWindow)
        self.actionredu.setObjectName("actionredu")
        self.actionrefresh = QtWidgets.QAction(MainWindow)
        self.actionrefresh.setObjectName("actionrefresh")
        self.actionexample = QtWidgets.QAction(MainWindow)
        self.actionexample.setObjectName("actionexample")
        self.menuopen_recent.addAction(self.actionexample)
        self.menustart.addAction(self.actionopendir)
        self.menustart.addAction(self.actionopenfile)
        self.menustart.addAction(self.menuopen_recent.menuAction())
        self.menustart.addSeparator()
        self.menustart.addAction(self.actionundo)
        self.menustart.addAction(self.actionredu)
        self.menustart.addAction(self.actionrefresh)
        self.menustart.addSeparator()
        self.menubar.addAction(self.menustart.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.data_info.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">数据信息：</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">第？/？份数据。</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">设备号：？；</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">日期：？；</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">状态：未分类/正常/异常/弃用</p></body></html>"))
        self.breath_label.setText(_translate("MainWindow", "breath(呼吸)"))
        self.int_label.setText(_translate("MainWindow", "index(体动)"))
        self.heart_label.setText(_translate("MainWindow", "heart(心率)"))
        self.data_info_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">快捷键：</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">shift + W：正常           shift + ↓：异常    Delete：弃用</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">shift + A：前一张           shift + D：后一张</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Ctrl + z：撤销    Ctrl + y：重做    Ctrl + w：关闭此窗口</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">= ：下一张未分类的数据    -：第一个未分类的数据</p></body></html>"))
        self.prev_b.setText(_translate("MainWindow", "pre(上一份)"))
        self.next_b.setText(_translate("MainWindow", "next(下一份)"))
        self.undo_b.setText(_translate("MainWindow", "undo(撤销)"))
        self.redo_b.setText(_translate("MainWindow", "redo(重做)"))
        self.nu_b.setWhatsThis(_translate("MainWindow", "To next unclassified Data(前进至下一张未分类数据)"))
        self.nu_b.setText(_translate("MainWindow", "Next Unclassified"))
        self.fu_b.setWhatsThis(_translate("MainWindow", "To next unclassified Data(前进至下一张未分类数据)"))
        self.fu_b.setText(_translate("MainWindow", "First Unclassified"))
        self.refresh_b.setText(_translate("MainWindow", "Refresh"))
        self.input_data_path.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">path_example</p></body></html>"))
        self.action_info.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">操作信息</p></body></html>"))
        self.class_abn_b.setText(_translate("MainWindow", "Abnorm(异常)"))
        self.class_n_b.setText(_translate("MainWindow", "Norm(正常)"))
        self.pushButton.setText(_translate("MainWindow", "Abandon(弃用)"))
        self.set_data_path.setText(_translate("MainWindow", "设置原文件路径"))
        self.set_work_path.setText(_translate("MainWindow", "设置工作路径"))
        self.menustart.setTitle(_translate("MainWindow", "start"))
        self.menuopen_recent.setTitle(_translate("MainWindow", "open_recent"))
        self.actionopendir.setText(_translate("MainWindow", "opendir"))
        self.actionopenfile.setText(_translate("MainWindow", "openfile"))
        self.actionundo.setText(_translate("MainWindow", "undo"))
        self.actionredu.setText(_translate("MainWindow", "redo"))
        self.actionrefresh.setText(_translate("MainWindow", "refresh"))
        self.actionexample.setText(_translate("MainWindow", "example"))
from pyqtgraph import PlotWidget
